global:
  scrape_interval: 5s
  external_labels:
    monitor: 'golangsvc'

scrape_configs:
  - job_name: 'golangsvc'
    metrics_path: /metrics
    scrape_interval: 4s
    static_configs:
      - targets: ['userservice:8080']